resources:
  - name: S_GoPublishBinary_0001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: Github
      path: rahulnlb1/go-pipe-test
      branches:
        include: main

pipelines:
  - name: pipeline_S_GoPublishBinary_0001
    steps:
      - name: S_GoPublishBinary_0001_1
        type: GoBuild
        configuration:
          inputResources:
            - name: S_GoPublishBinary_0001_GitRepo
          integrations:
            - name: arti
      - name: S_GoPublishBinary_0001_2
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: S_GoPublishBinary_0001_1
          integrations:
            - name: arti
          targetRepository: test-automation-go-local
